# Generated by Django 5.0.1 on 2024-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralizedHospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='hname',
        ),
        migrations.AddField(
            model_name='contactus',
            name='hid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
