# Generated by Django 5.0.1 on 2024-01-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralizedHospitalApp', '0002_remove_contactus_hname_contactus_hid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50)),
                ('doctorname', models.CharField(max_length=50)),
                ('doctorid', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('pnumber', models.BigIntegerField()),
                ('uhid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
