# Generated by Django 5.0.1 on 2024-01-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentralizedHospitalApp', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorid',
        ),
    ]
